### ISSUE TITLE
调仓提醒

### ISSUE THREAD

**Issue by FeMiner** [brain-zhang/kanglong#1]
且慢的调仓提醒会有延迟，每次收到调仓提醒已经过了下午3点

**Comment by brain-zhang** [comment]
这个影响不大，假如今天没有跟上调仓，明天波动 1%的话，我们平均每次买入不到总资金量的1%，所以波动在万分之一左右，长期来看晚跟一天的影响可以忽略不计；

且慢调仓有个"立即生效"的功能，为了我自己统计精确我一般没有采取“立即生效”；

为了达到完全精确，之后所有的调仓我都会选择“立即生效”，这样估计调仓提醒就会在交易时间段发出了；

**Comment by brain-zhang** [comment]
这个策略的原理已经说的很明白了；

我个人打算投入总仓位的30%； 目前已经投了8%左右；

所有的策略都有局限和风险，这个策略仅作参考；

**Comment by brain-zhang** [comment]
今天调仓点击了"立即生效"，看看提醒延时如何；
以后也会采取"立即生效"
